backend:
  name: git-gateway
  branch: master
media_folder: source/images
public_folder: /images
collections:
  - name: all_posts
    fields: &ref_0
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
        dateFormat: YYYY-MM-DD
        timeFormat: HH:mm:ss
        format: YYYY-MM-DD HH:mm:ss
        required: false
      - label: Tags
        name: tags
        widget: list
        required: false
      - label: Categories
        name: categories
        widget: list
        required: false
      - label: Body
        name: body
        widget: markdown
        required: false
      - label: Permalink
        name: permalink
        widget: string
        required: false
      - label: Comments
        name: comments
        widget: boolean
        default: true
        required: false
    label: Post
    folder: source/_posts
    create: true
    editor:
      preview: true
  - label: Page
    name: pages
    delete: false
    files:
      - name: css-index.md
        label: css
        file: source\css\index.md
        editor:
          preview: true
        fields: *ref_0
      - name: css-fluid-extension.css
        label: ''
        file: source\css\fluid-extension.css
        editor:
          preview: true
        fields: *ref_0
      - name: css-reset.min.css
        label: ''
        file: source\css\reset.min.css
        editor:
          preview: true
        fields: *ref_0
      - name: css-style.css
        label: ''
        file: source\css\style.css
        editor:
          preview: true
        fields: *ref_0
      - name: book-index.md
        label: 书单
        file: source\book\index.md
        editor:
          preview: true
        fields: *ref_0
      - name: example-index.md
        label: example
        file: source\example\index.md
        editor:
          preview: true
        fields: *ref_0
      - name: example-index.html
        label: ''
        file: source\example\index.html
        editor:
          preview: true
        fields: *ref_0
      - name: about-index.md
        label: WillMo
        file: source\about\index.md
        editor:
          preview: true
        fields: *ref_0
      - name: js-DynamicLine.js
        label: ''
        file: source\js\DynamicLine.js
        editor:
          preview: true
        fields: *ref_0
      - name: js-MyMath.js
        label: ''
        file: source\js\MyMath.js
        editor:
          preview: true
        fields: *ref_0
      - name: js-backgroundize.js
        label: ''
        file: source\js\backgroundize.js
        editor:
          preview: true
        fields: *ref_0
      - name: js-Stage.js
        label: ''
        file: source\js\Stage.js
        editor:
          preview: true
        fields: *ref_0
      - name: js-fscreen.js
        label: ''
        file: source\js\fscreen.js
        editor:
          preview: true
        fields: *ref_0
      - name: js-duration.js
        label: ''
        file: source\js\duration.js
        editor:
          preview: true
        fields: *ref_0
      - name: js-index.js
        label: ''
        file: source\js\index.js
        editor:
          preview: true
        fields: *ref_0
      - name: photos-index.md
        label: photos
        file: source\photos\index.md
        editor:
          preview: true
        fields: *ref_0
      - name: styles-backgroundize.css
        label: ''
        file: source\styles\backgroundize.css
        editor:
          preview: true
        fields: *ref_0
